// <auto-generated />
using System;
using ERPWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERPWebApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190824225352_CreateAllTables")]
    partial class CreateAllTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERPWebApi.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("DNI")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("Varchar(150)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("Logo")
                        .HasColumnType("Varchar(255)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Telefono1")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Telefono2")
                        .HasColumnType("Varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("ERPWebApi.Models.Entidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("DNI")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Direccion")
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("Varchar(60)");

                    b.Property<int>("EmpresaId");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombres")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Picture")
                        .HasColumnType("Varchar(255)");

                    b.Property<string>("Telefono1")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Telefono2")
                        .HasColumnType("Varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Entidad");
                });

            modelBuilder.Entity("ERPWebApi.Models.Funcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<bool>("EsActivo");

                    b.Property<bool>("EsBasico");

                    b.Property<bool>("EsGold");

                    b.Property<bool>("EsPlatinium");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int?>("RolId");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Funcion");
                });

            modelBuilder.Entity("ERPWebApi.Models.FuncionesPorRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<bool>("EsActivo");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<int>("FuncionId");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("RolId");

                    b.HasKey("Id");

                    b.HasIndex("FuncionId");

                    b.HasIndex("RolId");

                    b.ToTable("FuncionesPorRols");
                });

            modelBuilder.Entity("ERPWebApi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<decimal?>("CostoUCompra")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("EmpresaId");

                    b.Property<bool>("EsActivo");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("Varchar(150)");

                    b.Property<string>("Picture")
                        .HasColumnType("Varchar(255)");

                    b.Property<decimal>("PrecioMinimo")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("Numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ERPWebApi.Models.ProductoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("EmpresaId");

                    b.Property<bool>("EsActivo");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<decimal>("TasaItbis")
                        .HasColumnType("Numeric(6, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ProductoCategoria");
                });

            modelBuilder.Entity("ERPWebApi.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("EmpresaId");

                    b.Property<bool>("EsActivo");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("ERPWebApi.Models.SecuenciaNCF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("EmpresaId");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("NumeroAnterior");

                    b.Property<int>("NumeroMaximo");

                    b.Property<int>("PuntoReorden");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("SecuenciaNCF");
                });

            modelBuilder.Entity("ERPWebApi.Models.TipoNCF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<bool>("EsCompra");

                    b.Property<bool>("EsVenta");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasColumnType("Varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("TipoNCF");
                });

            modelBuilder.Entity("ERPWebApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("EmpresaId");

                    b.Property<int?>("EntidadId");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Picture")
                        .HasColumnType("Varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EntidadId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ERPWebApi.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("EmpresaId");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime?>("FechaAnulado");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("NCF")
                        .HasColumnType("Varchar(20)");

                    b.Property<long>("Numero");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<decimal>("TotalItbis")
                        .HasColumnType("Numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("ERPWebApi.Models.VentaAnulada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<int>("Motivo");

                    b.Property<int>("VentaId");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaAnulada");
                });

            modelBuilder.Entity("ERPWebApi.Models.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("EliminadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<DateTime>("FechaCreado");

                    b.Property<DateTime?>("FechaDeleted");

                    b.Property<DateTime?>("FechaModificado");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("Varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<int>("ProductoId");

                    b.Property<decimal>("TasaItbis")
                        .HasColumnType("Numeric(6, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("Numeric(18, 2)");

                    b.Property<int>("VentaId");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("VentaDetalle");
                });

            modelBuilder.Entity("ERPWebApi.Models.Entidad", b =>
                {
                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany("Entidades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.Funcion", b =>
                {
                    b.HasOne("ERPWebApi.Models.Rol")
                        .WithMany("Funciones")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.FuncionesPorRol", b =>
                {
                    b.HasOne("ERPWebApi.Models.Funcion", "Funcion")
                        .WithMany()
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPWebApi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.Producto", b =>
                {
                    b.HasOne("ERPWebApi.Models.ProductoCategoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.ProductoCategoria", b =>
                {
                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.Rol", b =>
                {
                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany("Roles")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.SecuenciaNCF", b =>
                {
                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.Usuario", b =>
                {
                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPWebApi.Models.Entidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.Venta", b =>
                {
                    b.HasOne("ERPWebApi.Models.Empresa", "Empresa")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.VentaAnulada", b =>
                {
                    b.HasOne("ERPWebApi.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ERPWebApi.Models.VentaDetalle", b =>
                {
                    b.HasOne("ERPWebApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPWebApi.Models.Venta", "Venta")
                        .WithOne("Items")
                        .HasForeignKey("ERPWebApi.Models.VentaDetalle", "VentaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
